### ISSUE TITLE
Upgrade plugin for grails 2.5.0

### ISSUE THREAD

**Issue by samuelzyx** [fterrier/grails-mail-on-exception#7]
It's don't work in grails 2.4.\* and grails 2.5.0

exception.ExceptionHandler could not send email after exception
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
    at org.chai.exception.ExceptionHandler$_resolveException_closure2.doCall(ExceptionHandler.groovy:65)
    at grails.plugin.mail.MailService.sendMail(MailService.groovy:53)
    at grails.plugin.mail.MailService.sendMail(MailService.groovy:59)

just right here

class ExceptionHandler extends GrailsExceptionResolver {
try {
                mailService.sendMail {
                    ....
                    html g.renderException(exception: exception) //cast null to integer
                }
            } catch (Exception e) {
                if (log.errorEnabled) log.error("could not send email after exception", e)
            }
}

**Comment by drmichaelgorski** [comment]
+1
